version: 43.0.9
pageUuid: 4f836806-9d96-11ed-b3ca-3f25faa9b9dc
appTemplate:
  appThemeId: 1
  folders:
    - JS_List_Values
    - Change_Request
    - Materials
    - JS_Payloads
    - Submit
    - Components
  queryStatusVisibility: false
  rootScreen: null
  version: 2.99.3
  markdownLinkBehavior: auto
