version: 43.0.9
pageUuid: af0cc58c-9383-11ed-b777-6f5d60c8cb59
appTemplate:
  appThemeId: 1
  folders:
    - importQueries
    - js_state
  queryStatusVisibility: false
  rootScreen: null
  version: 2.99.3
  markdownLinkBehavior: auto
