version: 43.0.9
pageUuid: 90f140f4-935c-11ed-83ce-d78042190159
appTemplate:
  appThemeId: 1
  folders:
    - CONSTS
    - Custom_Attribute
    - app_js
  queryStatusVisibility: false
  rootScreen: null
  version: 2.99.3
  markdownLinkBehavior: auto
