version: 43.0.9
pageUuid: a9c8b86e-9cc6-11ed-861a-338b7fe6027a
appTemplate:
  folders:
    - listQuery
    - Scenario
    - js
    - BoM_Materials
    - module_outputs
  queryStatusVisibility: false
  rootScreen: null
  isGlobalWidget: true
  version: 2.99.3
  markdownLinkBehavior: auto
