version: 43.0.9
pageUuid: a8b5c5fe-912f-11ed-9325-1b14f1a257de
appTemplate:
  appThemeId: 1
  folders:
    - epr_reports
    - epr_detail
  queryStatusVisibility: false
  rootScreen: null
  version: 2.99.3
  markdownLinkBehavior: auto
