id: productEPRTaxTitle
type: widget
subtype: TextWidget2
template:
  ordered:
    - heightType: auto
    - horizontalAlign: left
    - hidden: false
    - imageWidth: fit
    - showInEditor: false
    - verticalAlign: center
    - tooltipText: ''
    - value: '#### Top Product by EPR Tax'
    - disableMarkdown: false
    - overflowType: scroll
    - maintainSpaceWhenHidden: false
style:
  ordered: []
position2:
  position2:
    container: tabbedContainer3
    rowGroup: header
    height: 0.8
    width: 6
createdAt: 2023-01-10T21:31:32.204Z
