id: productEPRTaxTableTitle
type: widget
subtype: TextWidget2
template:
  ordered:
    - heightType: auto
    - horizontalAlign: center
    - hidden: false
    - imageWidth: fit
    - showInEditor: false
    - verticalAlign: center
    - tooltipText: ''
    - value: '#### Top Product by EPR Tax Paid'
    - disableMarkdown: false
    - overflowType: scroll
    - maintainSpaceWhenHidden: false
style:
  ordered: []
position2:
  position2:
    container: analyticsProductEPRTaxTable
    subcontainer: 93ced
    row: 0.1999999999999993
    height: 1.2
    width: 12
createdAt: 2023-01-10T21:58:18.410Z
