id: productEPRTaxChart
type: widget
subtype: PlotlyChartWidget
template:
  ordered:
    - dataseries:
        ordered:
          - '0':
              ordered:
                - label: TAX PAID
                - datasource: '{{getTopProductEPRTax.data[''sum'']}}'
                - chartType: bar
                - aggregationType: sum
                - color: '#033663'
                - colors:
                    ordered: []
                - visible: true
                - hovertemplate: '<b>%{x}</b><br>%{fullData.name}: %{y}<extra></extra>'
    - isDataTemplateDirty: true
    - datasource: ''
    - isJsonTemplateDirty: false
    - groupByDropdown: ''
    - datasourceInputMode: javascript
    - datasourceDataType: object
    - layout: ''
    - xAxisDropdown: product
    - data: ''
    - isStackSeriesEnabled: false
    - xAxisTickFormat: ''
    - skipDatasourceUpdate: false
    - datasourceJS: '{{getTopProductEPRTax.data}}'
    - yAxisTickFormat: ''
    - datasourcePluginType: null
    - xAxisType: default
    - datasourcePluginId: null
    - legendAlignment: right
    - isLayoutJsonDirty: false
    - chartType: bar
    - title: ''
    - xAxis: '{{getTopProductEPRTax.data.product}}'
    - groupByMode: dropdown
    - onPointSelectQuery: ''
    - xAxisMode: dropdown
    - shouldShowLegend: false
    - yAxisTitle: ''
    - selectedPoints:
        array: []
    - xAxisTitle: ''
    - groupByJS: ''
style:
  ordered: []
position2:
  position2:
    container: tabbedContainer3
    subcontainer: 268fc
    row: -5.551115123125783e-17
    height: 7
    width: 12
createdAt: 2023-01-27T23:06:01.575Z
