version: 43.0.9
pageUuid: 172e88c0-7d5f-11ed-af41-ef6d8d7b9dd7
appTemplate:
  folders:
    - Waste_Transportation
    - Waste_Product_Sold
    - Waste_After_Consumption
    - module_outputs
    - listQueries
  queryStatusVisibility: false
  rootScreen: null
  isGlobalWidget: true
  version: 2.99.3
  markdownLinkBehavior: auto
