version: 43.0.9
pageUuid: d6d3c26c-5c71-11ed-8186-c738f8a6bae3
appTemplate:
  folders:
    - listQueries
    - Component
    - BillOfMaterial
    - js
    - Product
    - Generate_Values
    - editChangeRequest_bom
  rootScreen: null
  isGlobalWidget: true
  version: 2.99.3
