version: 43.0.9
pageUuid: 09dee174-9cf4-11ed-ab83-6b170ed4bf76
appTemplate:
  appThemeId: 1
  folders:
    - listQueries
  queryStatusVisibility: false
  rootScreen: null
  version: 2.99.3
  markdownLinkBehavior: auto
