version: 43.0.9
pageUuid: 6f1b459c-7c87-11ed-b030-f78e12b7af56
appTemplate:
  folders:
    - listQuery
    - Scenario
    - js
    - BoM_Materials
    - Upstream_Transportation
    - Waste_Treatment
    - Start_Simulation
    - module_outputs
    - jp_Scratch
  queryStatusVisibility: false
  rootScreen: null
  isGlobalWidget: true
  version: 2.99.3
  markdownLinkBehavior: auto
