version: 43.0.9
pageUuid: 9e61e87c-906b-11ed-98d4-2f9968c91ea1
appTemplate:
  appThemeId: 1
  folders:
    - CONSTS
    - listQuery
  queryStatusVisibility: false
  rootScreen: null
  version: 2.99.3
  markdownLinkBehavior: auto
