id: environmentalImpactTable
type: widget
subtype: TableWidget
template:
  ordered:
    - showCustomButton: false
    - sortMappedValue:
        ordered: []
    - _filteredSortedRenderedDataWithTypes: null
    - heightType: fixed
    - normalizedData: null
    - rowHeight: standard
    - saveChangesDisabled: ''
    - columnTypeProperties:
        ordered:
          - material_id:
              ordered:
                - optionData: '{{ currentColumn }}'
                - colorMode: auto
                - allowCustomValue: true
                - optionLabels: []
                - optionColors: []
                - optionValues: []
          - total_cost:
              ordered:
                - showSeparators: true
                - currency: USD
                - padDecimal: true
          - material_code:
              ordered:
                - optionData: '{{ currentColumn }}'
                - colorMode: auto
                - allowCustomValue: true
                - optionLabels: []
                - optionColors: []
                - optionValues: []
          - material_name:
              ordered:
                - optionData: '{{ currentColumn }}'
                - colorMode: auto
                - allowCustomValue: true
                - optionLabels:
                    array: []
                - optionColors:
                    array: []
                - optionValues:
                    array: []
    - columnWidths:
        - object:
            id: quantity
            value: 82.80555725097656
        - object:
            id: uom
            value: 215.263916015625
        - object:
            id: total_cost
            value: 322.920166015625
    - showSummaryFooter: false
    - disableRowSelectInteraction: true
    - columnWidthsMobile: []
    - hasNextAfterCursor: ''
    - columnTypeSpecificExtras:
        ordered: []
    - onRowAdded: ''
    - columnHeaderNames:
        ordered:
          - material_code: Material
          - material_global_code: Global Identifier
          - quantity: Quantity
          - uom: UOM
          - total_cost: Cost ({{LS01.value.bom_material_breakdown[i].currency}})
          - material_name: Material Name
    - alwaysShowPaginator: false
    - columnColors:
        ordered:
          - photochemical_ozone: ''
          - from_country: ''
          - bio_diversity_unit: ''
          - acidification: ''
          - shipping_type_code: ''
          - val: ''
          - acidification_unit: ''
          - bio_diversity: ''
          - photochemical_ozone_unit: ''
          - material_name: ''
          - marine_eutrophication_unit: ''
          - water_use_unit: ''
          - material_code: ''
          - co2: ''
          - material: ''
          - ecotoxicity: ''
          - human_toxicity_non_cancer: ''
          - bom_material_breakdown: ''
          - total_cost: ''
          - scenario_id: ''
          - terrestrial_eutrophication: ''
          - quantity: ''
          - ionizing_radiation: ''
          - ozone_depletion_unit: ''
          - freshwater_eutrophication_unit: ''
          - fossil: ''
          - bom_materials: ''
          - human_toxicity_cancer_unit: ''
          - resource_use_unit: ''
          - upstream_transportation: ''
          - land_use_unit: ''
          - currency: ''
          - production_quantity: ''
          - particulate_matter_unit: ''
          - material_global_code: ''
          - to_country: ''
          - particulate_matter: ''
          - uom: ''
          - land_use: ''
          - material_id: ''
          - resource_use: ''
          - human_toxicity_cancer: ''
          - fossil_unit: ''
          - freshwater_eutrophication: ''
          - ozone_depletion: ''
          - ionizing_radiation_unit: ''
          - terrestrial_eutrophication_unit: ''
          - id: ''
          - human_toxicity_non_cancer_unit: ''
          - ecotoxicity_unit: ''
          - upstream_breakdown: ''
          - co2_unit: ''
          - key: ''
          - water_use: ''
          - marine_eutrophication: ''
    - columnFrozenAlignments:
        ordered: []
    - allowMultiRowSelect: false
    - columnFormats:
        ordered:
          - material_id: SingleTagDataCell
          - total_cost: CurrencyDataCell
          - material_code: SingleTagDataCell
          - material_name: SingleTagDataCell
    - columnRestrictedEditing:
        ordered: []
    - showFilterButton: false
    - _columnVisibility:
        ordered:
          - photochemical_ozone: false
          - from_country: false
          - bio_diversity_unit: false
          - acidification: false
          - shipping_type_code: false
          - acidification_unit: false
          - bio_diversity: false
          - photochemical_ozone_unit: false
          - marine_eutrophication_unit: false
          - water_use_unit: false
          - material_code: false
          - co2: false
          - ecotoxicity: false
          - human_toxicity_non_cancer: false
          - scenario_id: false
          - terrestrial_eutrophication: false
          - ionizing_radiation: false
          - ozone_depletion_unit: false
          - freshwater_eutrophication_unit: false
          - fossil: false
          - human_toxicity_cancer_unit: false
          - resource_use_unit: false
          - land_use_unit: false
          - currency: false
          - production_quantity: false
          - particulate_matter_unit: false
          - to_country: false
          - particulate_matter: false
          - land_use: false
          - material_id: false
          - resource_use: false
          - human_toxicity_cancer: false
          - fossil_unit: false
          - freshwater_eutrophication: false
          - ozone_depletion: false
          - ionizing_radiation_unit: false
          - terrestrial_eutrophication_unit: false
          - id: false
          - human_toxicity_non_cancer_unit: false
          - ecotoxicity_unit: false
          - co2_unit: false
          - water_use: false
          - marine_eutrophication: false
    - _columnSummaryTypes:
        ordered:
          - material_id: ''
          - total_cost: sum
          - material_code: ''
          - material_name: ''
    - _columnsWithLegacyBackgroundColor:
        set: []
    - showAddRowButton: false
    - _unfilteredSelectedIndex: null
    - nextBeforeCursor: ''
    - columnVisibility:
        ordered: []
    - selectedPageIndex: '0'
    - applyDynamicSettingsToColumnOrder: true
    - rowColor:
        array: []
    - actionButtonColumnName: Actions
    - resetAfterSave: true
    - filterStackType: and
    - downloadRawData: false
    - showFetchingIndicator: true
    - serverPaginated: false
    - data: '{{LS01.value.bom_material_breakdown.concat(LS01.value.bom_materials) }}'
    - displayedData: null
    - actionButtons: []
    - actionButtonSelectsRow: true
    - selectRowByDefault: true
    - defaultSortByColumn: ''
    - paginationOffset: 0
    - columnAlignment:
        ordered:
          - material_id: left
          - total_cost: right
          - material_code: left
          - material_name: left
    - columnSummaries:
        object: {}
    - showBoxShadow: false
    - sortedDesc: false
    - customButtonName: ''
    - columnMappersRenderAsHTML:
        ordered: []
    - showRefreshButton: false
    - pageSize: '20'
    - useDynamicColumnSettings: false
    - actionButtonPosition: left
    - dynamicRowHeights: false
    - bulkUpdateAction: ''
    - afterCursor: ''
    - onCustomButtonPressQueryName: ''
    - changeSet:
        object: {}
    - sortedColumn: ''
    - _columnSummaryValues:
        ordered:
          - material_id: ''
          - total_cost: ''
          - material_code: ''
          - material_name: ''
    - checkboxRowSelect: true
    - _compatibilityMode: false
    - showColumnBorders: false
    - clearSelectionLabel: Clear selection
    - _renderedDataWithTypes: null
    - columnAllowOverflow:
        ordered: []
    - beforeCursor: ''
    - serverPaginationType: limitOffsetBased
    - onRowSelect: ''
    - showDownloadButton: false
    - selectedIndex: null
    - defaultSortDescending: false
    - _sortedDisplayedDataIndices: null
    - dynamicColumnSettings: null
    - totalRowCount: ''
    - recordUpdates:
        array: []
    - newRow: null
    - emptyMessage: No rows found
    - columnEditable:
        ordered:
          - acidification_unit: false
          - water_use_unit: false
          - material_code: false
          - scenario_id: false
          - resource_use_unit: false
          - land_use_unit: false
          - material_id: false
          - id: false
          - ecotoxicity_unit: false
    - _viewerColumnSummaryTypes:
        object: {}
    - filters:
        array: []
    - displayedDataIndices: null
    - disableSorting:
        ordered: []
    - columnMappers:
        ordered:
          - material_id: ''
          - material_code: ''
          - material_name: ''
    - showClearSelection: false
    - doubleClickToEdit: false
    - overflowType: pagination
    - _reverseSortedDisplayedDataIndices: null
    - showTableBorder: false
    - selectedCell:
        object:
          index: null
          data: null
          columnName: null
    - columns: []
    - defaultSelectedRow: first
    - freezeActionButtonColumns: false
    - sort: null
    - _columns:
        - id
        - material_name
        - material_code
        - material_id
        - material_global_code
        - quantity
        - uom
        - total_cost
        - currency
        - fossil
        - co2_unit
        - co2
        - land_use
        - water_use
        - to_country
        - ecotoxicity
        - fossil_unit
        - scenario_id
        - from_country
        - resource_use
        - acidification
        - bio_diversity
        - land_use_unit
        - water_use_unit
        - ozone_depletion
        - ecotoxicity_unit
        - resource_use_unit
        - acidification_unit
        - bio_diversity_unit
        - ionizing_radiation
        - particulate_matter
        - shipping_type_code
        - photochemical_ozone
        - production_quantity
        - ozone_depletion_unit
        - human_toxicity_cancer
        - marine_eutrophication
        - ionizing_radiation_unit
        - particulate_matter_unit
        - photochemical_ozone_unit
        - freshwater_eutrophication
        - human_toxicity_non_cancer
        - human_toxicity_cancer_unit
        - marine_eutrophication_unit
        - terrestrial_eutrophication
        - freshwater_eutrophication_unit
        - human_toxicity_non_cancer_unit
        - terrestrial_eutrophication_unit
    - sortByRawValue:
        ordered: []
    - calculatedColumns: []
    - selectedRow:
        object:
          index: null
          data: null
    - showPaginationOnTop: false
    - _reverseDisplayedDataIndices: null
    - nextAfterCursor: ''
    - useCompactMode: false
style:
  ordered: []
position2:
  position2:
    row: 14.800000000000002
    height: 9
    width: 12
createdAt: 2023-01-13T14:38:04.971Z
