version: 43.0.9
pageUuid: 2eb6acda-6495-11ed-97ae-c3622b426d4b
appTemplate:
  appThemeId: 1
  folders:
    - listQueries
    - app_js
  queryStatusVisibility: false
  rootScreen: null
  version: 2.99.3
  markdownLinkBehavior: auto
