id: updateCustomValuesPayload
type: function
subtype: Function
template:
  ordered:
    - funcBody: |-
        const existingValues = {{getCustomAttributes.data.custom_values[0]}}
        const formData = {{jsonSchemaForm1.data}}
              if(!existingValues) {
                return JSON.stringify(formData)
              }

        const final = {...existingValues, formData}

        return JSON.stringify(formData)
    - value: ''
createdAt: 2023-02-02T16:30:17.098Z
folder: enhanced
