id: productBoxBomLink
type: widget
subtype: LinkWidget
template:
  ordered:
    - horizontalAlign: center
    - clickable: false
    - iconAfter: ''
    - hidden: false
    - text: View BOM
    - showUnderline: always
    - showInEditor: false
    - tooltipText: ''
    - allowWrap: false
    - iconBefore: ''
    - events:
        - ordered:
            - event: click
            - type: util
            - method: openApp
            - pluginId: ''
            - targetId: null
            - params:
                ordered:
                  - uuid: 315f38b2-5c57-11ed-92b5-63c0c5fe5649
                  - options:
                      ordered:
                        - queryParams:
                            - ordered:
                                - key: productId
                                - value: '{{ getProject.data.product_id[0] }}'
            - waitType: debounce
            - waitMs: '0'
    - loading: false
    - loaderPosition: auto
    - disabled: false
    - maintainSpaceWhenHidden: false
style:
  ordered: []
position2:
  position2:
    container: containerProduct
    subcontainer: fe2fa
    row: 1.8
    col: 7
    height: 0.6
    width: 5
createdAt: 2023-01-31T11:51:18.961Z
