id: productBoxMaterialCodeText
type: widget
subtype: TextWidget2
template:
  ordered:
    - heightType: auto
    - horizontalAlign: left
    - hidden: false
    - imageWidth: fit
    - showInEditor: false
    - verticalAlign: center
    - tooltipText: ''
    - value: 'Material Code: {{ getMaterialByProductId.data.material_code}}'
    - disableMarkdown: false
    - overflowType: scroll
    - maintainSpaceWhenHidden: false
style:
  ordered: []
position2:
  position2:
    container: containerProduct
    subcontainer: fe2fa
    row: 1.8
    height: 0.6
    width: 7
createdAt: 2023-01-31T11:43:39.623Z
